### ISSUE TITLE
Could not find com.mikhailovskii.kmp:in-app-review-kmp:1.0.7

### ISSUE THREAD

**Issue by joelkanyi** [SergeiMikhailovskii/kmp-app-review#31]
Getting the following error when I add the library to `commonMain` dependencies section. 

Kotlin: 1.9.22
Compose Multiplatform: 1.6.0

```gradle
* What went wrong:
   > Could not find com.mikhailovskii.kmp:in-app-review-kmp:1.0.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom
       - https://repo.maven.apache.org/maven2/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom
       - https://jitpack.io/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom
     Required by:
         project :shared
```

**Comment by RanaNadeemAslam** [comment]
I am also facing the same issue with the library. 
```
Could not find com.mikhailovskii.kmp:in-app-review-kmp:1.0.6.
Required by:
    project :composeApp
    
    Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.mikhailovskii.kmp:in-app-review-kmp:1.0.6.
```
I am using kotlin version: 1.9.21
compose version: 1.6.1

mavenCentral() is already added

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam @joelkanyi Hi! thanks for the feedback, I'll investigate this problem tomorrow

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam @joelkanyi hi! updated the setup info in the readme. tl;dr - you need to specify the repository in settings.gradle.kts - like this

```kotlin
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.pkg.github.com/SergeiMikhailovskii/kmp-app-review")
        }
    }
}
```

the repo will be moved to another storage but not in the nearest future I think

**Comment by RanaNadeemAslam** [comment]
@SergeiMikhailovskii hi, thank you for updating the readme, it will be helpful. I have tried again by adding this url in settings.gradle.kts but still its giving me error and its related to the authentication.

`Could not GET 'https://maven.pkg.github.com/SergeiMikhailovskii/kmp-app-review/com/mikhailovskii/kmp/in-app-review-kmp/1.0.7/in-app-review-kmp-1.0.7.pom'. Received status code 401 from server: Unauthorized`

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam hi! can u please try to add the credentials, like

```kotlin
maven(url = "https://maven.pkg.github.com/SergeiMikhailovskii/kmp-app-review") {
            credentials {
                username = your_username
                password = your_pat_token
            }
        }
```

**Comment by RanaNadeemAslam** [comment]
@SergeiMikhailovskii how can I get username and token?

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam username = RanaNadeemAslam and here's the doc about the token generation - https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by RanaNadeemAslam** [comment]
@SergeiMikhailovskii I have tried this but still getting the same error.

`maven(url = "https://maven.pkg.github.com/SergeiMikhailovskii/kmp-app-review") {
            credentials {
                username = "RanaNadeemAslam"
                password = "ghp_0rtn....................."
            }
        }`

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam does the token has read:packages permission?

<img width="615" alt="image" src="https://github.com/SergeiMikhailovskii/kmp-app-review/assets/33265881/9a504642-3e46-4454-a37a-b864dfe31aac">

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam hi, any news here?

**Comment by RanaNadeemAslam** [comment]
@SergeiMikhailovskii Yes the token has both read and write permissions. BTW, the lib should be on public so every body can access it without token etc. Hopefully you will be working on it also.

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam can u please attach the code snippet how u delcare the repository? there's a problem with publishing anywhere else is that JitPack doesn't support KMP and Sonatype isn't available free. So I don't see any other solution now(

**Comment by SergeiMikhailovskii** [comment]
@RanaNadeemAslam hi, any news here?

**Comment by SergeiMikhailovskii** [comment]
@joelkanyi hi, did u try this solution?

https://github.com/SergeiMikhailovskii/kmp-app-review/issues/31#issuecomment-1987751276

**Comment by joelkanyi** [comment]
Hey @SergeiMikhailovskii I didn't try it out because I don't want to use GitHub token. I don't know why @RanaNadeemAslam decided to host the library on GitHub other than maven central. With his permission I can fork the repo and publish it on my Maven Central account 

cc @RanaNadeemAslam

**Comment by saroyama** [comment]
for me this works:

`maven {
            url "https://maven.pkg.github.com/SergeiMikhailovskii/kmp-app-review"
            credentials {
                username "USER_NAME"
                password "API_KEY"
            }
        }`

**Comment by SergeiMikhailovskii** [comment]
Hi @joelkanyi! I published it to github maven since I had a template for it and didn't have an experience in publishing to maven central. but yes, I agree, that it's not a convinient way to add a separate repo with the credentials. closing the issue since the current solution works (thanks to the @saroyama proof) but created a separate issue to publish it to maven central (#47)

**Comment by SergeiMikhailovskii** [comment]
@joelkanyi @RanaNadeemAslam published to the maven central and updated the readme
